apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: K8sE2ETestContainerAllowedImages
spec:
  crd:
    spec:
      names:
        kind: K8sE2ETestContainerAllowedImages
        listKind: K8sE2ETestContainerAllowedImagesList
        plural: k8se2etestcontainerallowedimages
        singular: k8se2etestcontainerallowedimages
      match:
        kinds:
        - apiGroups:
          - ""
          kinds:
          - Pod
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            imageRegex:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package K8sE2ETestContainerAllowedImages

        violation[{"msg": msg}] {
          container := input_containers[_]
          not re_match(input.parameters.imageRegex, container.image)
          msg := sprintf("Container image %v for container %v has not been allowed.", [container.image, container.name])
        }

        input_containers[c] {
            c := input.review.object.spec.containers[_]
        }
        input_containers[c] {
            c := input.review.object.spec.initContainers[_]
        }